version: '3.8'

services:
  todo-app:
    build: .

    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=betadb
      - POSTGRES_USER=user
    
    image: postgres:latest
    
    