package main

import (
	"database/sql"
	"fmt"
	"log"

	//"net/http"

	_ "github.com/lib/pq"

	_ "github.com/BeHappych/lastPlease/docs"
	//"github.com/gin-gonic/gin"
	//swaggerFiles "github.com/swaggo/files"
	//ginSwagger "github.com/swaggo/gin-swagger"
)

type List struct {
	Id        string `json:"id"`
	Full_name string `json:"full_name"`
	Birthday  string `json:"birthday"`
	Address   string `json:"address"`
}

var database *sql.DB

func main() {

	db, err := sql.Open("postgres", "user=user password=pass dbname=betadb dbport=5432 sslmode=disable")
	if err != nil {
		log.Println(err)
	}
	database = db
	defer db.Close()
	//id := 2
	//database.Exec("delete from Lists where id = $1", id)
	database.Exec("CREATE TABLE betadb.Lists ( id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, full_name  varchar(30) NOT NULL, birthday date NOT NULL, address varchar(30) NOT NULL );")
	database.Exec("insert into betadb.Lists (full_name, birthday, address) values ('Gfdsf', '1/2/1990', 'dasf'), ('Gfdsf', '1/2/1990', 'dasf'), ('Gfdsf', '1/2/1990', 'dasf');")
	fmt.Println(database.Exec("SELECT * FROM betadb.Lists;"))

}
